{{ if eq (env "AUTH_PROXY") "enable"}}
http:
  middlewares:
    auth:
      basicAuth:
        usersFile: "/etc/traefik/auth/usersfile"
    authBackend:
      headers:
        customRequestHeaders:
          Authorization: "Basic {{ printf "%s:%s" (default "admin" (env "NUTANIX_USERNAME")) (env "NUTANIX_PASSWORD") | b64enc }}"
{{end}}
