# GET url
{{ $GETendpoints := list
"/api/nutanix/v2.0/storage_containers"
}}

# POST url
{{ $POSTendpoints := list
}}

# PUT url
{{ $PUTendpoints := list
}}

# DELETE url
{{ $DELETEendpoints := list
}}

{{define "route"}}
    {{ randAlphaNum 10 }}:
      entryPoints:
        - "proxy"
      rule: "Host(`{{ default "FQDN_not_configured" (env "FQDN") }}`) && PathPrefix(`{{.Prefix}}`) && Method(`{{.Method}}`)"
      service: nutanix-pc
      tls: {}
{{ if eq (env "AUTH_PROXY") "enable"}}
      middlewares:
        - auth
        - authBackend
{{end}}
{{end}}

http:
  routers:
{{range $prefix := $GETendpoints}}
{{ template "route" dict "Prefix" $prefix "Method" "GET"}}
{{end}}
{{range $prefix := $POSTendpoints}}
{{ template "route" dict "Prefix" $prefix "Method" "POST"}}
{{end}}
{{range $prefix := $PUTendpoints}}
{{ template "route" dict "Prefix" $prefix "Method" "PUT"}}
{{end}}
{{range $prefix := $DELETEendpoints}}
{{ template "route" dict "Prefix" $prefix "Method" "DELETE"}}
{{end}}