version: '3.1'

services:

  ntnx-api-proxy:
    image: ghcr.io/nutanix-cloud-native/ntnx-api-proxy
    restart: always
    ports:
      - 9440:9440
      # - 8080:8080
    environment:
      FQDN: proxy-pc.demo.com
      NUTANIX_ENDPOINT: pc.demo.com
      # TRAEFIK_LOG_LEVEL: "info"
      # TRAEFIK_SERVERSTRANSPORT_ROOTCAS: /etc/traefik/cert/ca.cer
      # DASHBOARD: enable
      # TRAEFIK_METRICS_PROMETHEUS="true"
    volumes:
      - ./cert:/etc/traefik/cert
      # - ./auth:/etc/traefik/auth
