version: '3.1'

services:

  ntnx-api-proxy:
    image: ghcr.io/nutanix-cloud-native/ntnx-api-proxy
    restart: always
    ports:
      - 9440:9440
      # - 8080:8080
    environment:
      FQDN: proxy-pc.demo.com
      NUTANIX_ENDPOINT: pc.demo.com
      # TRAEFIK_LOG_LEVEL: "info"
      #TRAEFIK_LOG_FORMAT: "json"
      #TRAEFIK_ACCESSLOG_FORMAT: "json"
      # TRAEFIK_SERVERSTRANSPORT_ROOTCAS: /etc/traefik/cert/ca.cer
      # DASHBOARD: enable
      # TRAEFIK_METRICS_PROMETHEUS: true
      # NOFILTER: true
    volumes:
      - ./cert:/etc/traefik/cert
      # - ./auth:/etc/traefik/auth
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # vector:
  #   image: timberio/vector:0.46.1-debian
  #   user: root
  #   environment:
  #     VLOGS_URI: ${VLOGS_URI}
  #   volumes:
  #     - ./vector.yaml:/etc/vector/vector.yaml
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - ntnx-api-proxy
