version: '3.1'

services:

  ntnx-api-proxy:
    image: ghcr.io/nutanix-cloud-native/ntnx-api-proxy
    restart: always
    ports:
      - 9440:9440
    environment:
      FQDN: proxy-pc.demo.com
      NUTANIX_ENDPOINT: pc.demo.com
      # TRAEFIK_LOG_LEVEL: "info"
      # TRAEFIK_SERVERSTRANSPORT_ROOTCAS: /etc/traefik/cert/ca.cer
      # AUTH_PROXY: enable
      # NUTANIX_USERNAME: admin
      # NUTANIX_PASSWORD: Bik7Tr750!
      # DASHBOARD: enable
    volumes:
      - ./cert:/etc/traefik/cert
      # - ./auth:/etc/traefik/auth
